### ISSUE TITLE
decrease core clock

### ISSUE THREAD

**Issue by rharunzade** [p4block/radeonjet#1]
How to decrease core clock? 
It can to increase only.

**Comment by p4block** [comment]
`amdgpu` only supports positive overclock percentages as far as I know. Manually echoing i.e. -4 to the sysdevice will kill the driver and require a reboot under most circumstances. (probably the input is not sanitized and it tried overclocking to a magical `-%`)

Downclock support will be added if/when they add it to the kernel, that's for sure.
